import RootLayout from "./RootLayout";

export const metadata = {
  title: "Divine Solitaire",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon/favicon-32x32.png",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
