import RootLayout from "./RootLayout";

export const metadata = {
  title: "Divine Solitaire",
  description: "Generated by BhumiSoftech",
  icons: {
    icon: "/favicon/favicon-32x32.png",
  },
  robots: "noindex, nofollow", // Blocks search engine indexing
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
